### ISSUE TITLE
inspectlet.com

### ISSUE THREAD

**Issue by crssi** [betterwebleon/slovenian-list#4]
Hi,
rule `@@||cdn.inspectlet.com/inspectlet.js$script,domain=1nadan.si` should be removed.
It is used only for tracking and I can't see any breakages on a page when I block the `inspectlet.com` doman.

Cheers

**Comment by betterwebleon** [comment]
Hello,
I checked it out. The reason for keeping the mentioned exception rule is because the following rule
`||inspectlet.com^$third-party`
from *EasyPrivacy* filter list (and also from *Spyware filter*) blocks some pictures on the website 1nadan.si.

You can see the difference [here](https://imgur.com/ZqjYH9t) (the comparison has been taken [from this example link](https://1nadan.si/ponudba/Potovanja/53566/super-cena-za-3-dnevni-pomladni-oddih-za-2-osebi-v-hotelu-zvonimir-4-v-baski-na-krku-2x-nocitev-s-polpenzionom-v-superior-sobi-z-balkonom-na-morski-st)).
Therefore I can't remove the exception rule.
Anyway, thanks for pointing it out!

Regards

**Comment by crssi** [comment]
I see, but even if I hardblock your rule with `||inspectlet.com^$important,third-party` I can't reproduce culprit in upper example URL. I still get all the pictures.
Can you check again?
Thank you in advanced and cheers from LJ ;)

**Comment by betterwebleon** [comment]
Sorry my bad, it must have been a coincidence before. The problem related to missing pictures is somewhere else. [Fixed.](https://github.com/betterwebleon/slovenian-list/commit/41a59bdef659073af2cf9902fe09040e9e41941c)
Thanks again, regards
